### ISSUE TITLE
JavaScript error when clicking "New Entry"

### ISSUE THREAD

**Issue by BernhardEh** [fochlac/Tempo-Tracker#12]
Seems after updating to 3.5.3 there is an error when trying to add a new entry:

```
popup.js:1066 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'key')
    at Ae.sc [as constructor] (popup.js:1066:933)
    at Ae.Vp [as render] (popup.js:1:9904)
    at ma (popup.js:1:7401)
    at Rc (popup.js:1:2803)
    at qp (popup.js:1:9140)
    at ma (popup.js:1:7952)
    at Rc (popup.js:1:2803)
    at ma (popup.js:1:7617)
    at Rc (popup.js:1:2803)
    at qp (popup.js:1:9140)
```

Not sure if it is important, but I'm using Atlassian Cloud.

**Comment by fochlac** [comment]
I think it's caused if you do not have any issues in your issue list but only use a JQL query to populate your selection. I did not grab the remote issues via jql when creating the new item and only relied on the issues that were manually added. I'll release a patch with a fix.

**Comment by fochlac** [comment]
it's already published, so you can just update I guess :)

**Comment by BernhardEh** [comment]
Works again 🥇
